### ISSUE TITLE
System.ArgumentOutOfRangeException for parameter "seconds"

### ISSUE THREAD

**Issue by UGamer** [kamranayub/igdb-dotnet#10]
The following code

`var games = await mainWindow.igdbClient.QueryAsync<IGDB.Models.Game>(IGDB.IGDBClient.Endpoints.Games, query: "search \"" + SearchBox.Text + "\"; fields *,platforms.*,platforms.versions.platform_logo.image_id,release_dates.*,release_dates.platform.*,involved_companies.*,involved_companies.company.*,genres.*,keywords.*,franchise.*,screenshots.image_id,artworks.image_id,cover.image_id; limit 18;")`

with "No More Heroes 2" replacing SearchBox.Text gives me this exception:
![image](https://user-images.githubusercontent.com/1571982/104496988-b5a01a00-55a7-11eb-9ae7-20dcc1ace7a2.png)
![image](https://user-images.githubusercontent.com/1571982/104497053-cea8cb00-55a7-11eb-82f1-b3eb12f16b31.png)

**Comment by UGamer** [comment]
Other SearchBox.Text replacements that cause this issue:
Sengoku 3, King of Fighters 97, The Last Blade, The Last Blade 2, Last Blade

**Comment by kamranayub** [comment]
Looks like it is due to this:

```json
"slug": "d4-enterprise",
          "start_date": -62135683200,
          "start_date_category": 2,
          "updated_at": 1587686400,
          "url": "https://www.igdb.com/companies/d4-enterprise",
          "websites": [
            3560
          ],
          "checksum": "d969c986-d85d-e84c-e4b9-682fb210176a"
```

😱 

This should be treated as having no date, it's invalid.

**Comment by kamranayub** [comment]
I think the problem is that the time is in _milliseconds_

![image](https://user-images.githubusercontent.com/563819/140459090-a9a15fa3-6480-4538-8bb3-6e3e26d9271c.png)

This needs to change to `FromUnixTimeMilliseconds`
