### ISSUE TITLE
QA : How do I get artworks by game id?

### ISSUE THREAD

**Issue by DineshSolanki** [kamranayub/igdb-dotnet#13]
I can get the artworks  of a game by calling the game endpoint with field artwork, -
```csharp
public async Artworks GetArtworksByGameId(string id)
        {
            var r = await IGDBClient.QueryAsync<Game>(IGDBClient.Endpoints.Games,
                $"fields id, artworks.*; where id = {id};");
            return r.First().Artworks.Values;
        }
```
which would give me the artwork object or the values, whichever we want,

but I'm thinking there has to be a way to get artworks by game id -
[this wrapper](https://github.com/CarlosLanderas/igdb-rs/blob/50dbb4b932f950afcd7e2a3f029752d0a8d0c970/examples/game_media_download.rs#L27-L28) seems to do something like that.

Is there a way to achieve this here?

**Comment by kamranayub** [comment]
Yeah, it looks like it's a request to Artworks endpoint and passing `game = id`

"Artwork – IGDB API docs" https://api-docs.igdb.com#artwork

Does that work for you?

**Comment by DineshSolanki** [comment]
that worked.
I was trying game.id , which was giving me random results.
Thanks.
