### ISSUE TITLE
QueryAsync to return Count

### ISSUE THREAD

**Issue by ThomasBowen** [kamranayub/igdb-dotnet#26]
A query request returns a count as `x-count` part of the headers.

Add an optional out parameter to QueryAsync to output this count and remove the need to call "Query" and "Count" when you are doing paginated search.

**Comment by kamranayub** [comment]
Thanks for the suggestion.

Docs: https://github.com/kamranayub/igdb-dotnet?tab=readme-ov-file#handling-query-counts

Example:

https://github.com/kamranayub/igdb-dotnet/blob/0f9f4ce7583f98d08d13e5cba2fabcdfc2dd14f3/IGDB.Tests/Games.cs#L31-L46
