### ISSUE TITLE
Missing models

### ISSUE THREAD

**Issue by gancarzradoslaw** [kamranayub/igdb-dotnet#31]
Hey,

I've noticed that there are missing some models:

- GameLocalization
- LanguageSupport
- LanguageSupportType
- Language
- Region
- ReleaseDateStatus

Is it intended or can be added?

**Comment by zachauker** [comment]
Bumping this, I have forked the repo to add the missing endpoints for my own project, but it would be nice for this to be included in the package!

**Comment by kamranayub** [comment]
Closed in #29
