### ISSUE TITLE
Migrate to v4

### ISSUE THREAD

**Issue by kamranayub** [kamranayub/igdb-dotnet#7]
https://api-docs.igdb.com/#upgrading-to-v4-from-v3

This will be a BC I expect. Due by October 26.

**Comment by DineshSolanki** [comment]
does the #8 fully migrate this to v4?

**Comment by kamranayub** [comment]
Yes, it should work but I'll be testing it with my existing codebase shortly to see if there are any other issues.

**Comment by DineshSolanki** [comment]
Yeah, take your time please, your library helped a lot. Thanks
