### ISSUE TITLE
Implementation of 'ITokenStore'

### ISSUE THREAD

**Issue by DineshSolanki** [kamranayub/igdb-dotnet#9]
**will store it statically in memory.**, do you mean that the access token is stored in the main memory and destroyed after the system is shut down or the application is shut down?

PS: I didn't Know where to ask that, so I created this Issue?

**Comment by kamranayub** [comment]
@DineshSolanki Good question -- yes, it is basically stored in a `static` variable which means it will live only as long as the DLL is loaded in memory, which is usually the lifetime of your application. The token is valid for 60 days and it is automatically refreshed when it expires.

This would not be as desirable in a situation where you may be spawning multiple processes or across application servers. In that case you will have to implement a persistent cache, like with Redis or similar backend.

**Comment by DineshSolanki** [comment]
okay, so even when you say the token is valid for 60 days, here in this case it is always obtained whenever application is started again, as we don't have the old token to test validity? am I correct?

**Comment by DineshSolanki** [comment]
Thanks, I'm cleared of my doubt 🙂, I will then store it in a local JSON file, I think that will be better.

**Comment by kamranayub** [comment]
@DineshSolanki Yep, that's correct. Some programs could possibly live that long but in my experience that's pretty impressive 😄 Long-running jobs (I use Azure WebJobs SDK) could run for days but usually the server has patches or something that causes them to restart anyway before 60 days.

**Comment by kamranayub** [comment]
> I will then store it in a local JSON file, I think that will be better.

Cool, feel free to make your package public and I can link to it so others can use it!

**Comment by DineshSolanki** [comment]
> 
> 
> @DineshSolanki Yep, that's correct. Some programs could possibly live that long but in my experience that's pretty impressive 😄 Long-running jobs (I use Azure WebJobs SDK) could run for days but usually the server has patches or something that causes them to restart anyway before 60 days.

@kamranayub yes, impressive😅, anyway, I'm sure my application won't live that long, It's a desktop WPF app.

**Comment by DineshSolanki** [comment]
> 
> 
> > I will then store it in a local JSON file, I think that will be better.
> 
> Cool, feel free to make your package public and I can link to it so others can use it!

okay, that seems good, and I would make it work for me, but I have no experience to as you said 'Package', do you mean a DLL? Sorry if these are a lot of questions

**Comment by DineshSolanki** [comment]
I have kind of implemented the interface, using [JotTracker](https://github.com/anakic/Jot) as I was already using that for my project.
However the **GetTokenAsync()** requires the **Task<TwitchAccessToken>** type as returnn but I have stored token in string, Any help on how to make it work?

**Comment by DineshSolanki** [comment]
Here what I came up with and it's working. As I was already using [JotTracker](https://github.com/anakic/Jot) in my project, This code also uses JotTracker to store the Token in a JSON File, as JotTracker itself does almost everything, I didn't have to do many changes from the **InMemoryToken** class.
```csharp
public class IGDBjotTrackerStore : BindableBase, ITokenStore
    {
        private TwitchAccessToken _currentToken;
        private TwitchAccessToken CurrentToken { get => _currentToken; set => SetProperty(ref _currentToken, value); }
       public IGDBjotTrackerStore()
        {
            Services.Tracker.Configure<IGDBjotTrackerStore>()
                .Property(p => p._currentToken)
                .PersistOn(nameof(PropertyChanged));
            Services.Tracker.Track(this);

        }
        public Task<TwitchAccessToken> GetTokenAsync()
        {
            return Task.FromResult(CurrentToken);
        }

        public Task<TwitchAccessToken> StoreTokenAsync(TwitchAccessToken token)
        {
            CurrentToken = token;
            return Task.FromResult(token);
        }
    }
}
```

**Comment by kamranayub** [comment]
Hey that's really neat, I'll add that as an example!

**Comment by DineshSolanki** [comment]
Thanks, sure.
